/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type UiLabels = {
  _id: string
  _type: 'uiLabels'
  _createdAt: string
  _updatedAt: string
  _rev: string
  learnMore?: LocaleString
  reachOut?: LocaleString
  connect?: LocaleString
  footerExplore?: LocaleString
  footerConnect?: LocaleString
  linkedin?: LocaleString
  mail?: LocaleString
}

export type LocaleString = {
  _type: 'localeString'
  en?: string
  es?: string
  zh?: string
  hi?: string
  fr?: string
  ar?: string
}

export type SkillCategoryLabels = {
  _id: string
  _type: 'skillCategoryLabels'
  _createdAt: string
  _updatedAt: string
  _rev: string
  technical?: LocaleString
  framework?: LocaleString
  library?: LocaleString
  tool?: LocaleString
  platform?: LocaleString
  design?: LocaleString
  language?: LocaleString
  cloudDevops?: LocaleString
  database?: LocaleString
  softSkill?: LocaleString
  other?: LocaleString
  all?: LocaleString
  frontend?: LocaleString
  backend?: LocaleString
  ai?: LocaleString
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type Navigation = {
  _id: string
  _type: 'navigation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  person: PersonReference
  logoText?: string
  navItems?: Array<
    {
      _key: string
    } & NavItem
  >
  ctaButton?: NavItem
}

export type NavItem = {
  _type: 'navItem'
  label: LocaleString
  linkType: 'anchor' | 'internal' | 'external'
  anchorId?: string
  externalUrl?: string
  openInNewTab?: boolean
  highlight?: boolean
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Portfolio = {
  _id: string
  _type: 'portfolio'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: LocaleString
  slug: Slug
  owner: PersonReference
  featuredProjects?: Array<
    {
      _key: string
    } & ProjectReference
  >
  sections?: Array<{
    sectionType:
      | 'about'
      | 'experience'
      | 'education'
      | 'projects'
      | 'skills'
      | 'certifications'
      | 'awards'
      | 'publications'
      | 'testimonials'
      | 'contact'
      | 'custom'
    sectionId: Slug
    internalTitle?: string
    showInNav?: boolean
    navLabel?: LocaleString
    heading?: LocaleString
    subheading?: LocaleText
    content?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    order?: number
    _type: 'section'
    _key: string
  }>
  favicon?: Icon
  appleTouchIcon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  themeColor?: string
  seo?: SeoMetadata
  websiteSchema?: WebSchema
}

export type WebSchema = {
  _type: 'webSchema'
  schemaType?: 'Person' | 'WebSite' | 'WebPage' | 'CreativeWork' | 'Article' | 'Organization'
  personJobTitle?: string
  personDescription?: LocaleText
  personSameAs?: Array<string>
  personAlumniOf?: string
  personWorksFor?: string
  websiteName?: LocaleString
  websiteUrl?: string
  pageName?: LocaleString
  pageUrl?: string
  pageBreadcrumb?: Array<{
    name?: string
    url?: string
    _type: 'breadcrumbItem'
    _key: string
  }>
  workName?: LocaleString
  workDescription?: LocaleText
  workUrl?: string
  workDateCreated?: string
  customJsonLd?: string
}

export type SeoMetadata = {
  _type: 'seoMetadata'
  metaTitle?: LocaleString
  metaDescription?: LocaleText
  keywords?: Array<string>
  canonicalUrl?: string
  ogTitle?: LocaleString
  ogDescription?: LocaleText
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: LocaleString
    _type: 'image'
  }
  ogType?: 'website' | 'profile' | 'article'
  twitterCard?: 'summary' | 'summary_large_image'
  twitterTitle?: LocaleString
  ogSiteName?: string
  twitterDescription?: LocaleText
  twitterImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: LocaleString
    _type: 'image'
  }
  noIndex?: boolean
  noFollow?: boolean
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Icon = {
  _type: 'icon'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: LocaleString
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Blog = {
  _id: string
  _type: 'blog'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: LocaleString
  slug: Slug
  category: 'Update' | 'News' | 'Shipping Notes' | 'Press Release'
  dek: LocaleText
  publishedDate: string
  author?: PersonReference
  isFeatured?: boolean
  coverImage: CustomImage
  stats?: Array<{
    value: string
    label?: string
    _type: 'stat'
    _key: string
  }>
  body?: BlogBlockContent
  footerLinks?: Array<{
    label: string
    url: string
    _type: 'footerLink'
    _key: string
  }>
  seo?: SeoMetadata
  structuredData?: WebSchema
}

export type BlogBlockContent = {
  _type: 'blogBlockContent'
  en?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & CalloutBox)
    | ({
        _key: string
      } & CodeSnippet)
    | ({
        _key: string
      } & ComparisonTable)
  >
  es?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & CalloutBox)
    | ({
        _key: string
      } & CodeSnippet)
    | ({
        _key: string
      } & ComparisonTable)
  >
  zh?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & CalloutBox)
    | ({
        _key: string
      } & CodeSnippet)
    | ({
        _key: string
      } & ComparisonTable)
  >
  hi?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & CalloutBox)
    | ({
        _key: string
      } & CodeSnippet)
    | ({
        _key: string
      } & ComparisonTable)
  >
  fr?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & CalloutBox)
    | ({
        _key: string
      } & CodeSnippet)
    | ({
        _key: string
      } & ComparisonTable)
  >
  ar?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & CalloutBox)
    | ({
        _key: string
      } & CodeSnippet)
    | ({
        _key: string
      } & ComparisonTable)
  >
}

export type CustomImage = {
  _type: 'customImage'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: LocaleString
  caption?: LocaleString
  credit?: string
}

export type LocaleText = {
  _type: 'localeText'
  en?: string
  es?: string
  zh?: string
  hi?: string
  fr?: string
  ar?: string
}

export type OrganizationReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'organization'
}

export type SkillReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'skill'
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: LocaleString
  slug: Slug
  description?: LocaleText
  body?: LocaleBlockContent
  projectUrl?: string
  repositoryUrl?: string
  startDate?: string
  endDate?: string
  isFeatured?: boolean
  coverImage?: CustomImage
  gallery?: Array<
    {
      _key: string
    } & CustomImage
  >
  thumbnail?: Icon
  contributors?: Array<
    {
      _key: string
    } & PersonReference
  >
  organization?: OrganizationReference
  skills?: Array<
    {
      _key: string
    } & SkillReference
  >
  seo?: SeoMetadata
  structuredData?: WebSchema
}

export type LocaleBlockContent = {
  _type: 'localeBlockContent'
  en?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h3' | 'h4' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  es?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h3' | 'h4' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  zh?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h3' | 'h4' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  hi?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h3' | 'h4' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  fr?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h3' | 'h4' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ar?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h3' | 'h4' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  person: PersonReference
  organization?: OrganizationReference
  relationship?: string
  quote: LocaleText
  rating?: number
  date?: string
}

export type Publication = {
  _id: string
  _type: 'publication'
  _createdAt: string
  _updatedAt: string
  _rev: string
  person: PersonReference
  coAuthors?: Array<
    {
      _key: string
    } & PersonReference
  >
  title: LocaleString
  publisher?: string
  description?: LocaleText
  url?: string
  publishedDate: string
}

export type Award = {
  _id: string
  _type: 'award'
  _createdAt: string
  _updatedAt: string
  _rev: string
  person: PersonReference
  title: LocaleString
  issuer?: OrganizationReference
  description?: LocaleText
  date: string
  url?: string
}

export type Certification = {
  _id: string
  _type: 'certification'
  _createdAt: string
  _updatedAt: string
  _rev: string
  person: PersonReference
  issuer: OrganizationReference
  title: LocaleString
  credentialId?: string
  credentialUrl?: string
  issueDate: string
  expiryDate?: string
}

export type Education = {
  _id: string
  _type: 'education'
  _createdAt: string
  _updatedAt: string
  _rev: string
  person: PersonReference
  institution?: OrganizationReference
  degree: LocaleString
  fieldOfStudy?: string
  description?: LocaleText
  startDate?: string
  endDate?: string
  isCurrent?: boolean
  grade?: string
}

export type Experience = {
  _id: string
  _type: 'experience'
  _createdAt: string
  _updatedAt: string
  _rev: string
  person: PersonReference
  organization?: OrganizationReference
  role: LocaleString
  employmentType?: 'full-time' | 'part-time' | 'contract' | 'freelance' | 'internship'
  location?: string
  startDate: string
  endDate?: string
  isCurrent?: boolean
  description?: LocaleText
  skills?: Array<
    {
      _key: string
    } & SkillReference
  >
}

export type Organization = {
  _id: string
  _type: 'organization'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: LocaleString
  slug: Slug
  description?: LocaleText
  website?: string
  industry?: string
  location?: string
  logo?: CustomImage
  logoMark?: Icon
  coverImage?: CustomImage
  seo?: SeoMetadata
  structuredData?: WebSchema
}

export type Skill = {
  _id: string
  _type: 'skill'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: LocaleString
  slug: Slug
  proficiency: number
  experience: number
  category?:
    | 'technical'
    | 'framework'
    | 'library'
    | 'tool'
    | 'platform'
    | 'design'
    | 'language'
    | 'cloud-devops'
    | 'database'
    | 'soft-skill'
    | 'other'
  filter_category?: 'all' | 'frontend' | 'backend' | 'ai' | 'others'
  iconName?: IconRef
}

export type IconRef = string

export type SectionReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'section'
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: LocaleString
  slug: Slug
  headline?: LocaleString
  bio_short?: LocaleBlockContent
  bio?: LocaleBlockContent
  greeting?: LocaleString
  header_title?: LocaleString
  logoImage?: CustomImage
  headerCta?: CtaButton
  channels?: Array<{
    label: LocaleString
    icon: Svg
    url: string
    openInNewTab?: boolean
    _key: string
  }>
  openToWork?: boolean
  openToWorkLabel?: LocaleString
  stats?: Array<{
    value: string
    label?: LocaleString
    _type: 'stat'
    _key: string
  }>
  featureHighlights?: Array<{
    iconName: IconRef
    kicker: string
    label: LocaleString
    _type: 'featureHighlight'
    _key: string
  }>
  featureIntro?: LocaleText
  featureLinkUrl?: string
  featureLinkLabel?: LocaleString
  primaryCta?: {
    text?: LocaleString
    href?: string
  }
  secondaryCta?: {
    text?: LocaleString
    href?: string
  }
  avatar?: CustomImage
  coverImage?: CustomImage
  resumeImage?: CustomImage
  email?: string
  phone?: string
  location?: LocaleString
  skills?: Array<
    {
      _key: string
    } & SkillReference
  >
  projects?: Array<
    {
      _key: string
    } & ProjectReference
  >
  socialProfiles?: Array<
    {
      _key: string
    } & SocialProfile
  >
  sections?: Array<
    {
      _key: string
    } & SectionReference
  >
  seo?: SeoMetadata
  structuredData?: WebSchema
  websiteSchema?: WebSchema
  isSiteAuthor?: boolean
}

export type Svg = {
  _type: 'svg'
  sourceSvg: InlineSvg
  strokeColor?: string
  fillColor?: string
  size?: string
  strokeWidth?: string
  strokeLinecap?: string
  strokeLinejoin?: string
  svg?: string
}

export type CtaButton = {
  _type: 'ctaButton'
  text: LocaleString
  href: string
  openInNewTab?: boolean
  isDownload?: boolean
  downloadFilename?: string
  rel?: Array<string>
  ariaLabel?: LocaleString
  ariaDescribedBy?: string
  title?: LocaleString
}

export type ComparisonTable = {
  _type: 'comparisonTable'
  caption?: string
  columns?: Array<
    {
      _key: string
    } & TableColumn
  >
  rows?: Array<
    | ({
        _key: string
      } & TableGroupRow)
    | ({
        _key: string
      } & TableDataRow)
  >
  footnote?: string
}

export type TableColumn = {
  _type: 'tableColumn'
  name: string
  descriptor?: string
  highlight?: boolean
}

export type TableDataRow = {
  _type: 'tableDataRow'
  label: string
  cells?: Array<
    {
      _key: string
    } & TableCell
  >
}

export type TableGroupRow = {
  _type: 'tableGroupRow'
  label: string
}

export type TableCell = {
  _type: 'tableCell'
  icon?: IconRef
  note?: string
}

export type CodeSnippet = {
  _type: 'codeSnippet'
  label?: string
  language?: string
  code: string
}

export type CalloutBox = {
  _type: 'calloutBox'
  label?: string
  text: LocaleText
}

export type Section = {
  _id: string
  _type: 'section'
  _createdAt: string
  _updatedAt: string
  _rev: string
  sectionType:
    | 'about'
    | 'experience'
    | 'education'
    | 'projects'
    | 'skills'
    | 'certifications'
    | 'awards'
    | 'publications'
    | 'testimonials'
    | 'contact'
    | 'custom'
  sectionId: Slug
  internalTitle?: string
  showInNav?: boolean
  navLabel?: LocaleString
  heading?: LocaleString
  subheading?: LocaleText
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  order?: number
}

export type SocialProfile = {
  _type: 'socialProfile'
  platform:
    | 'linkedin'
    | 'github'
    | 'twitter'
    | 'instagram'
    | 'dribbble'
    | 'behance'
    | 'youtube'
    | 'website'
    | 'other'
  url: string
  username?: string
}

export type InlineSvg = string

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | UiLabels
  | LocaleString
  | SkillCategoryLabels
  | PersonReference
  | Navigation
  | NavItem
  | ProjectReference
  | SanityImageAssetReference
  | Portfolio
  | WebSchema
  | SeoMetadata
  | SanityImageCrop
  | SanityImageHotspot
  | Icon
  | Slug
  | Blog
  | BlogBlockContent
  | CustomImage
  | LocaleText
  | OrganizationReference
  | SkillReference
  | Project
  | LocaleBlockContent
  | Testimonial
  | Publication
  | Award
  | Certification
  | Education
  | Experience
  | Organization
  | Skill
  | IconRef
  | SectionReference
  | Person
  | Svg
  | CtaButton
  | ComparisonTable
  | TableColumn
  | TableDataRow
  | TableGroupRow
  | TableCell
  | CodeSnippet
  | CalloutBox
  | Section
  | SocialProfile
  | InlineSvg
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
